vote: JmPotato as tikv reviewer
tikv/community pull request #188
Opened 2022-11-07 11:55 UTC by Connor1996

Signed-off-by: Connor1996 <zbk602423539@gmail.com>

2022-11-07 17:20 UTC, tonyxuqqi approved these changes

2022-11-09 02:18 UTC, JmPotato commented
cc @tikv/maintainers 

Please take a look, thx a lot.

2022-11-09 02:20 UTC, JmPotato commented
cc @BusyJay @hicqu @breezewish @innerr 

Please take a look, thx a lot.

2022-11-09 02:32 UTC, zhangjinpeng1987 approved these changes
+1 LGTM

2022-11-09 03:23 UTC, Connor1996 commented
/merge

2022-11-09 03:28 UTC, JmPotato requested changes

2022-11-09 03:28 UTC, JmPotato commented on votes/0188-JmPotato-as-tikv-reviewer.md
> +## Result
Maybe we should update the result before merging.

2022-11-09 03:56 UTC, BusyJay commented
As said in the poll,

> The vote will be open for at least 3 days unless there is an objection or not enough votes.

Don't hurry to merge.

2022-11-16 01:46 UTC, JmPotato commented on votes/0188-JmPotato-as-tikv-reviewer.md
> +## Result
@Connor1996 Hello, could we update the vote result and merge this PR now?

2022-11-16 20:42 UTC, skyzh commented
/merge

2022-11-16 20:43 UTC, skyzh commented
/cancel

2022-11-16 20:43 UTC, skyzh commented
I'll update the result

2022-11-16 20:48 UTC, merged